# Generated by ariadne-codegen
# Source: ./query_files/series-queries.graphql

from typing import Any

from .async_base_client import AsyncBaseClient
from .get_completed_series_details import GetCompletedSeriesDetails


def gql(q: str) -> str:
    return q


class SeriesClient(AsyncBaseClient):
    async def get_completed_series_details(
        self, id: str, **kwargs: Any
    ) -> GetCompletedSeriesDetails:
        query = gql(
            """
            query GetCompletedSeriesDetails($id: ID!) {
              seriesState(id: $id) {
                title {
                  nameShortened
                }
                draftActions {
                  sequenceNumber
                  drafter {
                    id
                  }
                  type
                  draftable {
                    name
                  }
                }
                valid
                updatedAt
                format
                started
                finished
                teams {
                  __typename
                  name
                  won
                }
                games(filter: {finished: true}) {
                  sequenceNumber
                  segments {
                    sequenceNumber
                    teams {
                      __typename
                      name
                      side
                      players {
                        __typename
                        ... on SegmentPlayerStateValorant {
                          name
                          headshots
                          damageDealt
                          damageTaken
                          currentArmor
                          currentHealth
                          damageDealtTargets {
                            target {
                              name
                            }
                            damageAmount
                            damageTypes {
                              type
                              damageAmount
                              occurrenceCount
                            }
                          }
                          damageDealtSources {
                            source {
                              name
                            }
                            damageAmount
                            damageTypes {
                              type
                              damageAmount
                              occurrenceCount
                            }
                          }
                          firstKill
                          kills
                          killAssistsGiven
                          killAssistsReceived
                          weaponKills {
                            weaponName
                            count
                          }
                          deaths
                          objectives {
                            type
                            completedFirst
                            completionCount
                          }
                        }
                      }
                    }
                  }
                  map {
                    name
                    bounds {
                      min {
                        x
                        y
                      }
                      max {
                        x
                        y
                      }
                    }
                  }
                  teams {
                    __typename
                    name
                    won
                    players {
                      __typename
                      name
                      character {
                        name
                        id
                      }
                      position {
                        x
                        y
                      }
                      inventory {
                        items {
                          name
                        }
                      }
                      kills
                      killAssistsGiven
                      killAssistsReceived
                      weaponKills {
                        weaponName
                        count
                      }
                      deaths
                      money
                      netWorth
                    }
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query,
            operation_name="GetCompletedSeriesDetails",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetCompletedSeriesDetails.model_validate(data)
