# Generated by ariadne-codegen
# Source: ./query_files/series-queries.graphql

from typing import Any

from .async_base_client import AsyncBaseClient
from .get_live_dota_series_state import GetLiveDotaSeriesState


def gql(q: str) -> str:
    return q


class SeriesClient(AsyncBaseClient):
    async def get_live_dota_series_state(self, **kwargs: Any) -> GetLiveDotaSeriesState:
        query = gql(
            """
            query GetLiveDotaSeriesState {
              seriesState(id: "2") {
                valid
                updatedAt
                format
                started
                finished
                teams {
                  __typename
                  name
                  won
                }
                games(filter: {started: true, finished: false}) {
                  sequenceNumber
                  teams {
                    __typename
                    name
                    players {
                      __typename
                      name
                      kills
                      deaths
                      netWorth
                      money
                      position {
                        x
                        y
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="GetLiveDotaSeriesState",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetLiveDotaSeriesState.model_validate(data)
