# Generated by ariadne-codegen
# Source: ./query_files/series-queries.graphql

from typing import Annotated, Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class GetCompletedSeriesDetails(BaseModel):
    series_state: Optional["GetCompletedSeriesDetailsSeriesState"] = Field(
        alias="seriesState"
    )


class GetCompletedSeriesDetailsSeriesState(BaseModel):
    draft_actions: list["GetCompletedSeriesDetailsSeriesStateDraftActions"] = Field(
        alias="draftActions"
    )
    valid: bool
    updated_at: Any = Field(alias="updatedAt")
    format: str
    started: bool
    finished: bool
    teams: list["GetCompletedSeriesDetailsSeriesStateTeams"]
    games: list["GetCompletedSeriesDetailsSeriesStateGames"]


class GetCompletedSeriesDetailsSeriesStateDraftActions(BaseModel):
    sequence_number: str = Field(alias="sequenceNumber")
    drafter: "GetCompletedSeriesDetailsSeriesStateDraftActionsDrafter"
    type: str
    draftable: "GetCompletedSeriesDetailsSeriesStateDraftActionsDraftable"


class GetCompletedSeriesDetailsSeriesStateDraftActionsDrafter(BaseModel):
    id: str


class GetCompletedSeriesDetailsSeriesStateDraftActionsDraftable(BaseModel):
    name: str


class GetCompletedSeriesDetailsSeriesStateTeams(BaseModel):
    typename__: Literal[
        "SeriesTeamState",
        "SeriesTeamStateCs2",
        "SeriesTeamStateCsgo",
        "SeriesTeamStateDefault",
        "SeriesTeamStateDota",
        "SeriesTeamStatePubg",
        "SeriesTeamStateR6",
        "SeriesTeamStateValorant",
    ] = Field(alias="__typename")
    name: str
    won: bool


class GetCompletedSeriesDetailsSeriesStateGames(BaseModel):
    sequence_number: int = Field(alias="sequenceNumber")
    segments: list["GetCompletedSeriesDetailsSeriesStateGamesSegments"]
    map: "GetCompletedSeriesDetailsSeriesStateGamesMap"
    teams: list["GetCompletedSeriesDetailsSeriesStateGamesTeams"]


class GetCompletedSeriesDetailsSeriesStateGamesSegments(BaseModel):
    sequence_number: int = Field(alias="sequenceNumber")
    teams: list["GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeams"]


class GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeams(BaseModel):
    typename__: Literal[
        "SegmentTeamState",
        "SegmentTeamStateCs2",
        "SegmentTeamStateCsgo",
        "SegmentTeamStateDefault",
        "SegmentTeamStateR6",
        "SegmentTeamStateValorant",
    ] = Field(alias="__typename")
    name: str
    players: list[
        Annotated[
            Union[
                "GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerState",
                "GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorant",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerState(
    BaseModel
):
    typename__: Literal[
        "SegmentPlayerState",
        "SegmentPlayerStateCs2",
        "SegmentPlayerStateCsgo",
        "SegmentPlayerStateDefault",
        "SegmentPlayerStateR6",
    ] = Field(alias="__typename")


class GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorant(
    BaseModel
):
    typename__: Literal["SegmentPlayerStateValorant"] = Field(alias="__typename")
    name: str
    headshots: int
    damage_dealt: int = Field(alias="damageDealt")
    damage_taken: int = Field(alias="damageTaken")
    current_armor: int = Field(alias="currentArmor")
    current_health: int = Field(alias="currentHealth")
    damage_dealt_targets: list[
        "GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtTargets"
    ] = Field(alias="damageDealtTargets")
    damage_dealt_sources: list[
        "GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtSources"
    ] = Field(alias="damageDealtSources")
    first_kill: bool = Field(alias="firstKill")
    kills: int
    kill_assists_given: int = Field(alias="killAssistsGiven")
    kill_assists_received: int = Field(alias="killAssistsReceived")
    weapon_kills: list[
        "GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantWeaponKills"
    ] = Field(alias="weaponKills")
    deaths: int
    objectives: list[
        "GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantObjectives"
    ]


class GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtTargets(
    BaseModel
):
    target: "GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtTargetsTarget"
    damage_amount: int = Field(alias="damageAmount")
    damage_types: list[
        "GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtTargetsDamageTypes"
    ] = Field(alias="damageTypes")


class GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtTargetsTarget(
    BaseModel
):
    name: str


class GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtTargetsDamageTypes(
    BaseModel
):
    type: str
    damage_amount: int = Field(alias="damageAmount")
    occurrence_count: int = Field(alias="occurrenceCount")


class GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtSources(
    BaseModel
):
    source: "GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtSourcesSource"
    damage_amount: int = Field(alias="damageAmount")
    damage_types: list[
        "GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtSourcesDamageTypes"
    ] = Field(alias="damageTypes")


class GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtSourcesSource(
    BaseModel
):
    name: str


class GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtSourcesDamageTypes(
    BaseModel
):
    type: str
    damage_amount: int = Field(alias="damageAmount")
    occurrence_count: int = Field(alias="occurrenceCount")


class GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantWeaponKills(
    BaseModel
):
    weapon_name: str = Field(alias="weaponName")
    count: Optional[int]


class GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantObjectives(
    BaseModel
):
    type: str
    completed_first: bool = Field(alias="completedFirst")
    completion_count: int = Field(alias="completionCount")


class GetCompletedSeriesDetailsSeriesStateGamesMap(BaseModel):
    name: str
    bounds: Optional["GetCompletedSeriesDetailsSeriesStateGamesMapBounds"]


class GetCompletedSeriesDetailsSeriesStateGamesMapBounds(BaseModel):
    min: "GetCompletedSeriesDetailsSeriesStateGamesMapBoundsMin"
    max: "GetCompletedSeriesDetailsSeriesStateGamesMapBoundsMax"


class GetCompletedSeriesDetailsSeriesStateGamesMapBoundsMin(BaseModel):
    x: float
    y: float


class GetCompletedSeriesDetailsSeriesStateGamesMapBoundsMax(BaseModel):
    x: float
    y: float


class GetCompletedSeriesDetailsSeriesStateGamesTeams(BaseModel):
    typename__: Literal[
        "GameTeamState",
        "GameTeamStateCs2",
        "GameTeamStateCsgo",
        "GameTeamStateDefault",
        "GameTeamStateDota",
        "GameTeamStateLol",
        "GameTeamStatePubg",
        "GameTeamStateR6",
        "GameTeamStateValorant",
    ] = Field(alias="__typename")
    name: str
    players: list["GetCompletedSeriesDetailsSeriesStateGamesTeamsPlayers"]


class GetCompletedSeriesDetailsSeriesStateGamesTeamsPlayers(BaseModel):
    typename__: Literal[
        "GamePlayerState",
        "GamePlayerStateCs2",
        "GamePlayerStateCsgo",
        "GamePlayerStateDefault",
        "GamePlayerStateDota",
        "GamePlayerStateLol",
        "GamePlayerStateMlbb",
        "GamePlayerStatePubg",
        "GamePlayerStateR6",
        "GamePlayerStateValorant",
    ] = Field(alias="__typename")
    name: str
    character: Optional[
        "GetCompletedSeriesDetailsSeriesStateGamesTeamsPlayersCharacter"
    ]
    inventory: "GetCompletedSeriesDetailsSeriesStateGamesTeamsPlayersInventory"
    kills: int
    kill_assists_given: int = Field(alias="killAssistsGiven")
    kill_assists_received: int = Field(alias="killAssistsReceived")
    weapon_kills: list[
        "GetCompletedSeriesDetailsSeriesStateGamesTeamsPlayersWeaponKills"
    ] = Field(alias="weaponKills")
    deaths: int
    money: int
    net_worth: int = Field(alias="netWorth")


class GetCompletedSeriesDetailsSeriesStateGamesTeamsPlayersCharacter(BaseModel):
    name: str
    id: str


class GetCompletedSeriesDetailsSeriesStateGamesTeamsPlayersInventory(BaseModel):
    items: list["GetCompletedSeriesDetailsSeriesStateGamesTeamsPlayersInventoryItems"]


class GetCompletedSeriesDetailsSeriesStateGamesTeamsPlayersInventoryItems(BaseModel):
    name: str


class GetCompletedSeriesDetailsSeriesStateGamesTeamsPlayersWeaponKills(BaseModel):
    weapon_name: str = Field(alias="weaponName")
    count: Optional[int]


GetCompletedSeriesDetails.model_rebuild()
GetCompletedSeriesDetailsSeriesState.model_rebuild()
GetCompletedSeriesDetailsSeriesStateDraftActions.model_rebuild()
GetCompletedSeriesDetailsSeriesStateGames.model_rebuild()
GetCompletedSeriesDetailsSeriesStateGamesSegments.model_rebuild()
GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeams.model_rebuild()
GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorant.model_rebuild()
GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtTargets.model_rebuild()
GetCompletedSeriesDetailsSeriesStateGamesSegmentsTeamsPlayersSegmentPlayerStateValorantDamageDealtSources.model_rebuild()
GetCompletedSeriesDetailsSeriesStateGamesMap.model_rebuild()
GetCompletedSeriesDetailsSeriesStateGamesMapBounds.model_rebuild()
GetCompletedSeriesDetailsSeriesStateGamesTeams.model_rebuild()
GetCompletedSeriesDetailsSeriesStateGamesTeamsPlayers.model_rebuild()
GetCompletedSeriesDetailsSeriesStateGamesTeamsPlayersInventory.model_rebuild()
