# Generated by ariadne-codegen
# Source: ./query_files/series-queries.graphql

from typing import Any, Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class GetLiveDotaSeriesState(BaseModel):
    series_state: Optional["GetLiveDotaSeriesStateSeriesState"] = Field(
        alias="seriesState"
    )


class GetLiveDotaSeriesStateSeriesState(BaseModel):
    valid: bool
    updated_at: Any = Field(alias="updatedAt")
    format: str
    started: bool
    finished: bool
    teams: list["GetLiveDotaSeriesStateSeriesStateTeams"]
    games: list["GetLiveDotaSeriesStateSeriesStateGames"]


class GetLiveDotaSeriesStateSeriesStateTeams(BaseModel):
    typename__: Literal[
        "SeriesTeamState",
        "SeriesTeamStateCs2",
        "SeriesTeamStateCsgo",
        "SeriesTeamStateDefault",
        "SeriesTeamStateDota",
        "SeriesTeamStatePubg",
        "SeriesTeamStateR6",
        "SeriesTeamStateValorant",
    ] = Field(alias="__typename")
    name: str
    won: bool


class GetLiveDotaSeriesStateSeriesStateGames(BaseModel):
    sequence_number: int = Field(alias="sequenceNumber")
    teams: list["GetLiveDotaSeriesStateSeriesStateGamesTeams"]


class GetLiveDotaSeriesStateSeriesStateGamesTeams(BaseModel):
    typename__: Literal[
        "GameTeamState",
        "GameTeamStateCs2",
        "GameTeamStateCsgo",
        "GameTeamStateDefault",
        "GameTeamStateDota",
        "GameTeamStateLol",
        "GameTeamStatePubg",
        "GameTeamStateR6",
        "GameTeamStateValorant",
    ] = Field(alias="__typename")
    name: str
    players: list["GetLiveDotaSeriesStateSeriesStateGamesTeamsPlayers"]


class GetLiveDotaSeriesStateSeriesStateGamesTeamsPlayers(BaseModel):
    typename__: Literal[
        "GamePlayerState",
        "GamePlayerStateCs2",
        "GamePlayerStateCsgo",
        "GamePlayerStateDefault",
        "GamePlayerStateDota",
        "GamePlayerStateLol",
        "GamePlayerStateMlbb",
        "GamePlayerStatePubg",
        "GamePlayerStateR6",
        "GamePlayerStateValorant",
    ] = Field(alias="__typename")
    name: str
    kills: int
    deaths: int
    net_worth: int = Field(alias="netWorth")
    money: int
    position: Optional["GetLiveDotaSeriesStateSeriesStateGamesTeamsPlayersPosition"]


class GetLiveDotaSeriesStateSeriesStateGamesTeamsPlayersPosition(BaseModel):
    x: float
    y: float


GetLiveDotaSeriesState.model_rebuild()
GetLiveDotaSeriesStateSeriesState.model_rebuild()
GetLiveDotaSeriesStateSeriesStateGames.model_rebuild()
GetLiveDotaSeriesStateSeriesStateGamesTeams.model_rebuild()
GetLiveDotaSeriesStateSeriesStateGamesTeamsPlayers.model_rebuild()
