# Generated by ariadne-codegen
# Source: https://api-op.grid.gg/live-data-feed/series-state/graphql

from typing import Optional

from .base_model import BaseModel


class GameStateFilter(BaseModel):
    started: Optional[bool] = None
    finished: Optional[bool] = None
