# Generated by ariadne-codegen
# Source: ./query_files/stats-feed-queries.graphql

from typing import Any

from .async_base_client import AsyncBaseClient
from .player_statistics_for_chosen_tournaments import (
    PlayerStatisticsForChosenTournaments,
)
from .player_statistics_for_last_three_months import PlayerStatisticsForLastThreeMonths
from .team_statistics_for_chosen_tournaments import TeamStatisticsForChosenTournaments
from .team_statistics_for_last_three_months import TeamStatisticsForLastThreeMonths


def gql(q: str) -> str:
    return q


class StatsClient(AsyncBaseClient):
    async def team_statistics_for_last_three_months(
        self, **kwargs: Any
    ) -> TeamStatisticsForLastThreeMonths:
        query = gql(
            """
            query TeamStatisticsForLastThreeMonths {
              teamStatistics(teamId: "83", filter: {timeWindow: LAST_3_MONTHS}) {
                id
                aggregationSeriesIds
                series {
                  __typename
                  count
                  kills {
                    sum
                    min
                    max
                    avg
                  }
                }
                game {
                  __typename
                  count
                  wins {
                    value
                    count
                    percentage
                    streak {
                      min
                      max
                      current
                    }
                  }
                }
                segment {
                  __typename
                  type
                  count
                  deaths {
                    sum
                    min
                    max
                    avg
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="TeamStatisticsForLastThreeMonths",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return TeamStatisticsForLastThreeMonths.model_validate(data)

    async def team_statistics_for_chosen_tournaments(
        self, **kwargs: Any
    ) -> TeamStatisticsForChosenTournaments:
        query = gql(
            """
            query TeamStatisticsForChosenTournaments {
              teamStatistics(teamId: "83", filter: {tournamentIds: {in: ["1", "2"]}}) {
                id
                aggregationSeriesIds
                series {
                  __typename
                  count
                  kills {
                    sum
                    min
                    max
                    avg
                  }
                }
                game {
                  __typename
                  count
                  wins {
                    value
                    count
                    percentage
                    streak {
                      min
                      max
                      current
                    }
                  }
                }
                segment {
                  __typename
                  type
                  count
                  deaths {
                    sum
                    min
                    max
                    avg
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="TeamStatisticsForChosenTournaments",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return TeamStatisticsForChosenTournaments.model_validate(data)

    async def player_statistics_for_last_three_months(
        self, **kwargs: Any
    ) -> PlayerStatisticsForLastThreeMonths:
        query = gql(
            """
            query PlayerStatisticsForLastThreeMonths {
              playerStatistics(playerId: "244", filter: {timeWindow: LAST_3_MONTHS}) {
                id
                aggregationSeriesIds
                series {
                  __typename
                  count
                  kills {
                    sum
                    min
                    max
                    avg
                  }
                }
                game {
                  __typename
                  count
                  wins {
                    value
                    count
                    percentage
                    streak {
                      min
                      max
                      current
                    }
                  }
                }
                segment {
                  __typename
                  type
                  count
                  deaths {
                    sum
                    min
                    max
                    avg
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="PlayerStatisticsForLastThreeMonths",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return PlayerStatisticsForLastThreeMonths.model_validate(data)

    async def player_statistics_for_chosen_tournaments(
        self, **kwargs: Any
    ) -> PlayerStatisticsForChosenTournaments:
        query = gql(
            """
            query PlayerStatisticsForChosenTournaments {
              playerStatistics(playerId: "244", filter: {tournamentIds: {in: ["1", "2"]}}) {
                id
                aggregationSeriesIds
                series {
                  __typename
                  count
                  kills {
                    sum
                    min
                    max
                    avg
                  }
                }
                game {
                  __typename
                  count
                  wins {
                    value
                    count
                    percentage
                    streak {
                      min
                      max
                      current
                    }
                  }
                }
                segment {
                  __typename
                  type
                  count
                  deaths {
                    sum
                    min
                    max
                    avg
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="PlayerStatisticsForChosenTournaments",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return PlayerStatisticsForChosenTournaments.model_validate(data)
