# Generated by ariadne-codegen
# Source: https://api-op.grid.gg/statistics-feed/graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import GameOrderField, OrderDirection, TimeRangeFilter


class BooleanFilter(BaseModel):
    equals: Optional[bool] = None


class CharacterFilter(BaseModel):
    id: Optional["IdFilter"] = None
    name: Optional["StringFilter"] = None


class DateTimeFilter(BaseModel):
    period: Optional[TimeRangeFilter] = None


class GameOrder(BaseModel):
    field: GameOrderField
    direction: OrderDirection


class GamePlayerStateFilter(BaseModel):
    character: Optional["CharacterFilter"] = None


class GameSelection(BaseModel):
    filter: Optional["GameStateFilter"] = None
    first: Optional[int] = None
    order_by: Optional[list["GameOrder"]] = Field(alias="orderBy", default=None)


class GameStateFilter(BaseModel):
    map: Optional["MapFilter"] = None
    teams: Optional["GameTeamStateFilter"] = None
    title_version: Optional["TitleVersionFilter"] = Field(
        alias="titleVersion", default=None
    )
    segments: Optional["SegmentStateFilter"] = None
    tournament_ids: Optional["IdFilter"] = Field(alias="tournamentIds", default=None)
    tournament: Optional["TeamGameStatisticsTournamentFilter"] = None
    time_window: Optional[TimeRangeFilter] = Field(alias="timeWindow", default=None)
    started_at: Optional["DateTimeFilter"] = Field(alias="startedAt", default=None)
    and_: Optional[list["GameStateFilter"]] = Field(alias="and", default=None)
    or_: Optional[list["GameStateFilter"]] = Field(alias="or", default=None)


class GameStatisticsFilter(BaseModel):
    tournament: Optional["GameStatisticsTournamentFilter"] = None
    started_at: Optional["DateTimeFilter"] = Field(alias="startedAt", default=None)
    version: Optional["GameStatisticsVersionFilter"] = None


class GameStatisticsTournamentFilter(BaseModel):
    id: Optional["IdFilter"] = None
    include_children: bool = Field(alias="includeChildren")


class GameStatisticsVersionFilter(BaseModel):
    id: Optional["IdFilter"] = None


class GameTeamStateFilter(BaseModel):
    id: Optional["IdFilter"] = None
    side: Optional["StringFilter"] = None
    objectives: Optional["ObjectiveFilter"] = None
    players: Optional["GamePlayerStateFilter"] = None
    first_kill: Optional["BooleanFilter"] = Field(alias="firstKill", default=None)


class IdFilter(BaseModel):
    in_: Optional[list[str]] = Field(alias="in", default=None)


class MapFilter(BaseModel):
    name: Optional["StringFilter"] = None


class ObjectiveFilter(BaseModel):
    type: Optional["StringFilter"] = None
    completed_first: Optional["BooleanFilter"] = Field(
        alias="completedFirst", default=None
    )


class PlayerStatisticsFilter(BaseModel):
    tournament_ids: Optional["IdFilter"] = Field(alias="tournamentIds", default=None)
    tournament: Optional["PlayerStatisticsTournamentFilter"] = None
    time_window: Optional[TimeRangeFilter] = Field(alias="timeWindow", default=None)
    started_at: Optional["DateTimeFilter"] = Field(alias="startedAt", default=None)


class PlayerStatisticsTournamentFilter(BaseModel):
    id: Optional["IdFilter"] = None
    include_children: bool = Field(alias="includeChildren")


class SegmentStateFilter(BaseModel):
    type: Optional["StringFilter"] = None
    won_first: Optional["BooleanFilter"] = Field(alias="wonFirst", default=None)


class SeriesStatisticsFilter(BaseModel):
    tournament: Optional["SeriesStatisticsTournamentFilter"] = None
    started_at: Optional["DateTimeFilter"] = Field(alias="startedAt", default=None)


class SeriesStatisticsTournamentFilter(BaseModel):
    id: Optional["IdFilter"] = None
    include_children: bool = Field(alias="includeChildren")


class StringFilter(BaseModel):
    contains: Optional[str] = None
    equals: Optional[str] = None


class TeamGameStatisticsTournamentFilter(BaseModel):
    id: Optional["IdFilter"] = None
    include_children: bool = Field(alias="includeChildren")


class TeamStatisticsFilter(BaseModel):
    tournament_ids: Optional["IdFilter"] = Field(alias="tournamentIds", default=None)
    tournament: Optional["TeamStatisticsTournamentFilter"] = None
    time_window: Optional[TimeRangeFilter] = Field(alias="timeWindow", default=None)
    started_at: Optional["DateTimeFilter"] = Field(alias="startedAt", default=None)


class TeamStatisticsTournamentFilter(BaseModel):
    id: Optional["IdFilter"] = None
    include_children: bool = Field(alias="includeChildren")


class TitleVersionFilter(BaseModel):
    name: Optional["StringFilter"] = None


CharacterFilter.model_rebuild()
GamePlayerStateFilter.model_rebuild()
GameSelection.model_rebuild()
GameStateFilter.model_rebuild()
GameStatisticsFilter.model_rebuild()
GameStatisticsTournamentFilter.model_rebuild()
GameStatisticsVersionFilter.model_rebuild()
GameTeamStateFilter.model_rebuild()
MapFilter.model_rebuild()
ObjectiveFilter.model_rebuild()
PlayerStatisticsFilter.model_rebuild()
PlayerStatisticsTournamentFilter.model_rebuild()
SegmentStateFilter.model_rebuild()
SeriesStatisticsFilter.model_rebuild()
SeriesStatisticsTournamentFilter.model_rebuild()
TeamGameStatisticsTournamentFilter.model_rebuild()
TeamStatisticsFilter.model_rebuild()
TeamStatisticsTournamentFilter.model_rebuild()
TitleVersionFilter.model_rebuild()
