# Generated by ariadne-codegen
# Source: ./query_files/stats-feed-queries.graphql

from typing import Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class PlayerStatisticsForChosenTournaments(BaseModel):
    player_statistics: "PlayerStatisticsForChosenTournamentsPlayerStatistics" = Field(
        alias="playerStatistics"
    )


class PlayerStatisticsForChosenTournamentsPlayerStatistics(BaseModel):
    id: str
    aggregation_series_ids: list[str] = Field(alias="aggregationSeriesIds")
    series: "PlayerStatisticsForChosenTournamentsPlayerStatisticsSeries"
    game: "PlayerStatisticsForChosenTournamentsPlayerStatisticsGame"
    segment: list["PlayerStatisticsForChosenTournamentsPlayerStatisticsSegment"]


class PlayerStatisticsForChosenTournamentsPlayerStatisticsSeries(BaseModel):
    typename__: Literal[
        "Cs2PlayerSeriesStatistics",
        "CsgoPlayerSeriesStatistics",
        "DefaultPlayerSeriesStatistics",
        "PlayerSeriesStatistics",
        "ValorantPlayerSeriesStatistics",
    ] = Field(alias="__typename")
    count: int
    kills: "PlayerStatisticsForChosenTournamentsPlayerStatisticsSeriesKills"


class PlayerStatisticsForChosenTournamentsPlayerStatisticsSeriesKills(BaseModel):
    sum: int
    min: int
    max: int
    avg: float


class PlayerStatisticsForChosenTournamentsPlayerStatisticsGame(BaseModel):
    typename__: Literal[
        "DefaultPlayerGameStatistics",
        "PlayerGameStatistics",
        "PlayerGameStatisticsCs2",
        "PlayerGameStatisticsCsgo",
        "PlayerGameStatisticsDota",
        "PlayerGameStatisticsLol",
        "PlayerGameStatisticsR6",
        "PlayerGameStatisticsVal",
    ] = Field(alias="__typename")
    count: int
    wins: list[Optional["PlayerStatisticsForChosenTournamentsPlayerStatisticsGameWins"]]


class PlayerStatisticsForChosenTournamentsPlayerStatisticsGameWins(BaseModel):
    value: bool
    count: int
    percentage: float
    streak: "PlayerStatisticsForChosenTournamentsPlayerStatisticsGameWinsStreak"


class PlayerStatisticsForChosenTournamentsPlayerStatisticsGameWinsStreak(BaseModel):
    min: int
    max: int
    current: int


class PlayerStatisticsForChosenTournamentsPlayerStatisticsSegment(BaseModel):
    typename__: Literal[
        "DefaultPlayerSegmentStatistics",
        "PlayerSegmentStatistics",
        "PlayerSegmentStatisticsCs2",
        "PlayerSegmentStatisticsCsgo",
        "PlayerSegmentStatisticsR6",
    ] = Field(alias="__typename")
    type: str
    count: int
    deaths: "PlayerStatisticsForChosenTournamentsPlayerStatisticsSegmentDeaths"


class PlayerStatisticsForChosenTournamentsPlayerStatisticsSegmentDeaths(BaseModel):
    sum: int
    min: int
    max: int
    avg: float


PlayerStatisticsForChosenTournaments.model_rebuild()
PlayerStatisticsForChosenTournamentsPlayerStatistics.model_rebuild()
PlayerStatisticsForChosenTournamentsPlayerStatisticsSeries.model_rebuild()
PlayerStatisticsForChosenTournamentsPlayerStatisticsGame.model_rebuild()
PlayerStatisticsForChosenTournamentsPlayerStatisticsGameWins.model_rebuild()
PlayerStatisticsForChosenTournamentsPlayerStatisticsSegment.model_rebuild()
