# Generated by ariadne-codegen
# Source: ./query_files/stats-feed-queries.graphql

from typing import Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class PlayerStatisticsForLastThreeMonths(BaseModel):
    player_statistics: "PlayerStatisticsForLastThreeMonthsPlayerStatistics" = Field(
        alias="playerStatistics"
    )


class PlayerStatisticsForLastThreeMonthsPlayerStatistics(BaseModel):
    id: str
    aggregation_series_ids: list[str] = Field(alias="aggregationSeriesIds")
    series: "PlayerStatisticsForLastThreeMonthsPlayerStatisticsSeries"
    game: "PlayerStatisticsForLastThreeMonthsPlayerStatisticsGame"
    segment: list["PlayerStatisticsForLastThreeMonthsPlayerStatisticsSegment"]


class PlayerStatisticsForLastThreeMonthsPlayerStatisticsSeries(BaseModel):
    typename__: Literal[
        "Cs2PlayerSeriesStatistics",
        "CsgoPlayerSeriesStatistics",
        "DefaultPlayerSeriesStatistics",
        "PlayerSeriesStatistics",
        "ValorantPlayerSeriesStatistics",
    ] = Field(alias="__typename")
    count: int
    kills: "PlayerStatisticsForLastThreeMonthsPlayerStatisticsSeriesKills"


class PlayerStatisticsForLastThreeMonthsPlayerStatisticsSeriesKills(BaseModel):
    sum: int
    min: int
    max: int
    avg: float


class PlayerStatisticsForLastThreeMonthsPlayerStatisticsGame(BaseModel):
    typename__: Literal[
        "DefaultPlayerGameStatistics",
        "PlayerGameStatistics",
        "PlayerGameStatisticsCs2",
        "PlayerGameStatisticsCsgo",
        "PlayerGameStatisticsDota",
        "PlayerGameStatisticsLol",
        "PlayerGameStatisticsR6",
        "PlayerGameStatisticsVal",
    ] = Field(alias="__typename")
    count: int
    wins: list[Optional["PlayerStatisticsForLastThreeMonthsPlayerStatisticsGameWins"]]


class PlayerStatisticsForLastThreeMonthsPlayerStatisticsGameWins(BaseModel):
    value: bool
    count: int
    percentage: float
    streak: "PlayerStatisticsForLastThreeMonthsPlayerStatisticsGameWinsStreak"


class PlayerStatisticsForLastThreeMonthsPlayerStatisticsGameWinsStreak(BaseModel):
    min: int
    max: int
    current: int


class PlayerStatisticsForLastThreeMonthsPlayerStatisticsSegment(BaseModel):
    typename__: Literal[
        "DefaultPlayerSegmentStatistics",
        "PlayerSegmentStatistics",
        "PlayerSegmentStatisticsCs2",
        "PlayerSegmentStatisticsCsgo",
        "PlayerSegmentStatisticsR6",
    ] = Field(alias="__typename")
    type: str
    count: int
    deaths: "PlayerStatisticsForLastThreeMonthsPlayerStatisticsSegmentDeaths"


class PlayerStatisticsForLastThreeMonthsPlayerStatisticsSegmentDeaths(BaseModel):
    sum: int
    min: int
    max: int
    avg: float


PlayerStatisticsForLastThreeMonths.model_rebuild()
PlayerStatisticsForLastThreeMonthsPlayerStatistics.model_rebuild()
PlayerStatisticsForLastThreeMonthsPlayerStatisticsSeries.model_rebuild()
PlayerStatisticsForLastThreeMonthsPlayerStatisticsGame.model_rebuild()
PlayerStatisticsForLastThreeMonthsPlayerStatisticsGameWins.model_rebuild()
PlayerStatisticsForLastThreeMonthsPlayerStatisticsSegment.model_rebuild()
