# Generated by ariadne-codegen
# Source: ./query_files/stats-feed-queries.graphql

from typing import Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class TeamStatisticsForLastThreeMonths(BaseModel):
    team_statistics: "TeamStatisticsForLastThreeMonthsTeamStatistics" = Field(
        alias="teamStatistics"
    )


class TeamStatisticsForLastThreeMonthsTeamStatistics(BaseModel):
    id: str
    aggregation_series_ids: list[str] = Field(alias="aggregationSeriesIds")
    series: "TeamStatisticsForLastThreeMonthsTeamStatisticsSeries"
    game: "TeamStatisticsForLastThreeMonthsTeamStatisticsGame"
    segment: list["TeamStatisticsForLastThreeMonthsTeamStatisticsSegment"]


class TeamStatisticsForLastThreeMonthsTeamStatisticsSeries(BaseModel):
    typename__: Literal[
        "Cs2TeamSeriesStatistics",
        "CsgoTeamSeriesStatistics",
        "DefaultTeamSeriesStatistics",
        "PubgTeamSeriesStatistics",
        "TeamSeriesStatistics",
    ] = Field(alias="__typename")
    count: int
    kills: "TeamStatisticsForLastThreeMonthsTeamStatisticsSeriesKills"


class TeamStatisticsForLastThreeMonthsTeamStatisticsSeriesKills(BaseModel):
    sum: int
    min: int
    max: int
    avg: float


class TeamStatisticsForLastThreeMonthsTeamStatisticsGame(BaseModel):
    typename__: Literal[
        "DefaultTeamGameStatistics",
        "TeamGameStatistics",
        "TeamGameStatisticsCs2",
        "TeamGameStatisticsCsgo",
        "TeamGameStatisticsDota",
        "TeamGameStatisticsLol",
        "TeamGameStatisticsR6",
        "TeamGameStatisticsVal",
    ] = Field(alias="__typename")
    count: int
    wins: list[Optional["TeamStatisticsForLastThreeMonthsTeamStatisticsGameWins"]]


class TeamStatisticsForLastThreeMonthsTeamStatisticsGameWins(BaseModel):
    value: bool
    count: int
    percentage: float
    streak: "TeamStatisticsForLastThreeMonthsTeamStatisticsGameWinsStreak"


class TeamStatisticsForLastThreeMonthsTeamStatisticsGameWinsStreak(BaseModel):
    min: int
    max: int
    current: int


class TeamStatisticsForLastThreeMonthsTeamStatisticsSegment(BaseModel):
    typename__: Literal[
        "DefaultTeamSegmentStatistics",
        "TeamSegmentStatistics",
        "TeamSegmentStatisticsCs2",
        "TeamSegmentStatisticsCsgo",
        "TeamSegmentStatisticsR6",
    ] = Field(alias="__typename")
    type: str
    count: int
    deaths: "TeamStatisticsForLastThreeMonthsTeamStatisticsSegmentDeaths"


class TeamStatisticsForLastThreeMonthsTeamStatisticsSegmentDeaths(BaseModel):
    sum: int
    min: int
    max: int
    avg: float


TeamStatisticsForLastThreeMonths.model_rebuild()
TeamStatisticsForLastThreeMonthsTeamStatistics.model_rebuild()
TeamStatisticsForLastThreeMonthsTeamStatisticsSeries.model_rebuild()
TeamStatisticsForLastThreeMonthsTeamStatisticsGame.model_rebuild()
TeamStatisticsForLastThreeMonthsTeamStatisticsGameWins.model_rebuild()
TeamStatisticsForLastThreeMonthsTeamStatisticsSegment.model_rebuild()
