# Generated by ariadne-codegen
# Source: ./query_files/stats-feed-queries.graphql

from typing import Literal, Optional

from pydantic import Field

from .base_model import BaseModel


class TeamStatisticsForChosenTournaments(BaseModel):
    team_statistics: "TeamStatisticsForChosenTournamentsTeamStatistics" = Field(
        alias="teamStatistics"
    )


class TeamStatisticsForChosenTournamentsTeamStatistics(BaseModel):
    id: str
    aggregation_series_ids: list[str] = Field(alias="aggregationSeriesIds")
    series: "TeamStatisticsForChosenTournamentsTeamStatisticsSeries"
    game: "TeamStatisticsForChosenTournamentsTeamStatisticsGame"
    segment: list["TeamStatisticsForChosenTournamentsTeamStatisticsSegment"]


class TeamStatisticsForChosenTournamentsTeamStatisticsSeries(BaseModel):
    typename__: Literal[
        "Cs2TeamSeriesStatistics",
        "CsgoTeamSeriesStatistics",
        "DefaultTeamSeriesStatistics",
        "PubgTeamSeriesStatistics",
        "TeamSeriesStatistics",
    ] = Field(alias="__typename")
    count: int
    kills: "TeamStatisticsForChosenTournamentsTeamStatisticsSeriesKills"


class TeamStatisticsForChosenTournamentsTeamStatisticsSeriesKills(BaseModel):
    sum: int
    min: int
    max: int
    avg: float


class TeamStatisticsForChosenTournamentsTeamStatisticsGame(BaseModel):
    typename__: Literal[
        "DefaultTeamGameStatistics",
        "TeamGameStatistics",
        "TeamGameStatisticsCs2",
        "TeamGameStatisticsCsgo",
        "TeamGameStatisticsDota",
        "TeamGameStatisticsLol",
        "TeamGameStatisticsR6",
        "TeamGameStatisticsVal",
    ] = Field(alias="__typename")
    count: int
    wins: list[Optional["TeamStatisticsForChosenTournamentsTeamStatisticsGameWins"]]


class TeamStatisticsForChosenTournamentsTeamStatisticsGameWins(BaseModel):
    value: bool
    count: int
    percentage: float
    streak: "TeamStatisticsForChosenTournamentsTeamStatisticsGameWinsStreak"


class TeamStatisticsForChosenTournamentsTeamStatisticsGameWinsStreak(BaseModel):
    min: int
    max: int
    current: int


class TeamStatisticsForChosenTournamentsTeamStatisticsSegment(BaseModel):
    typename__: Literal[
        "DefaultTeamSegmentStatistics",
        "TeamSegmentStatistics",
        "TeamSegmentStatisticsCs2",
        "TeamSegmentStatisticsCsgo",
        "TeamSegmentStatisticsR6",
    ] = Field(alias="__typename")
    type: str
    count: int
    deaths: "TeamStatisticsForChosenTournamentsTeamStatisticsSegmentDeaths"


class TeamStatisticsForChosenTournamentsTeamStatisticsSegmentDeaths(BaseModel):
    sum: int
    min: int
    max: int
    avg: float


TeamStatisticsForChosenTournaments.model_rebuild()
TeamStatisticsForChosenTournamentsTeamStatistics.model_rebuild()
TeamStatisticsForChosenTournamentsTeamStatisticsSeries.model_rebuild()
TeamStatisticsForChosenTournamentsTeamStatisticsGame.model_rebuild()
TeamStatisticsForChosenTournamentsTeamStatisticsGameWins.model_rebuild()
TeamStatisticsForChosenTournamentsTeamStatisticsSegment.model_rebuild()
