# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Any, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .get_all_series_in_next_24_hours import GetAllSeriesInNext24Hours
from .get_all_series_since_date import GetAllSeriesSinceDate
from .get_csgo_loopfeed_series import GetCsgoLoopfeedSeries
from .get_organization import GetOrganization
from .get_organizations import GetOrganizations
from .get_player import GetPlayer
from .get_players import GetPlayers
from .get_team_by_exact_name import GetTeamByExactName
from .get_team_by_similar_name import GetTeamBySimilarName
from .get_team_roster import GetTeamRoster
from .get_teams import GetTeams
from .get_tournament import GetTournament
from .get_tournaments import GetTournaments
from .series_formats import SeriesFormats


def gql(q: str) -> str:
    return q


class CentralDbClient(AsyncBaseClient):
    async def get_tournament(self, **kwargs: Any) -> GetTournament:
        query = gql(
            """
            query GetTournament {
              tournament(id: "1") {
                ...tournamentFields
              }
            }

            fragment tournamentFields on Tournament {
              id
              name
              nameShortened
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="GetTournament", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetTournament.model_validate(data)

    async def get_tournaments(self, **kwargs: Any) -> GetTournaments:
        query = gql(
            """
            query GetTournaments {
              tournaments {
                pageInfo {
                  hasPreviousPage
                  hasNextPage
                  startCursor
                  endCursor
                }
                totalCount
                edges {
                  cursor
                  node {
                    ...tournamentFields
                  }
                }
              }
            }

            fragment tournamentFields on Tournament {
              id
              name
              nameShortened
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="GetTournaments", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetTournaments.model_validate(data)

    async def get_csgo_loopfeed_series(self, **kwargs: Any) -> GetCsgoLoopfeedSeries:
        query = gql(
            """
            query GetCsgoLoopfeedSeries {
              series(id: "1") {
                ...seriesFields
              }
            }

            fragment seriesFields on Series {
              id
              title {
                nameShortened
              }
              tournament {
                nameShortened
              }
              startTimeScheduled
              format {
                name
                nameShortened
              }
              teams {
                baseInfo {
                  name
                }
                scoreAdvantage
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="GetCsgoLoopfeedSeries",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetCsgoLoopfeedSeries.model_validate(data)

    async def get_all_series_in_next_24_hours(
        self, **kwargs: Any
    ) -> GetAllSeriesInNext24Hours:
        query = gql(
            """
            query GetAllSeriesInNext24Hours {
              allSeries(
                filter: {startTimeScheduled: {gte: "2024-04-24T15:00:07+02:00", lte: "2024-04-25T15:00:07+02:00"}}
                orderBy: StartTimeScheduled
              ) {
                totalCount
                pageInfo {
                  hasPreviousPage
                  hasNextPage
                  startCursor
                  endCursor
                }
                edges {
                  cursor
                  node {
                    ...seriesFields
                  }
                }
              }
            }

            fragment seriesFields on Series {
              id
              title {
                nameShortened
              }
              tournament {
                nameShortened
              }
              startTimeScheduled
              format {
                name
                nameShortened
              }
              teams {
                baseInfo {
                  name
                }
                scoreAdvantage
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="GetAllSeriesInNext24Hours",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetAllSeriesInNext24Hours.model_validate(data)

    async def get_all_series_since_date(
        self, date_time: Union[Optional[str], UnsetType] = UNSET, **kwargs: Any
    ) -> GetAllSeriesSinceDate:
        query = gql(
            """
            query GetAllSeriesSinceDate($DateTime: String) {
              allSeries(
                filter: {startTimeScheduled: {gte: $DateTime}}
                orderBy: StartTimeScheduled
              ) {
                totalCount
                pageInfo {
                  hasPreviousPage
                  hasNextPage
                  startCursor
                  endCursor
                }
                edges {
                  cursor
                  node {
                    ...seriesFields
                  }
                }
              }
            }

            fragment seriesFields on Series {
              id
              title {
                nameShortened
              }
              tournament {
                nameShortened
              }
              startTimeScheduled
              format {
                name
                nameShortened
              }
              teams {
                baseInfo {
                  name
                }
                scoreAdvantage
              }
            }
            """
        )
        variables: dict[str, object] = {"DateTime": date_time}
        response = await self.execute(
            query=query,
            operation_name="GetAllSeriesSinceDate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetAllSeriesSinceDate.model_validate(data)

    async def series_formats(self, **kwargs: Any) -> SeriesFormats:
        query = gql(
            """
            query SeriesFormats {
              seriesFormats {
                id
                name
                nameShortened
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="SeriesFormats", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return SeriesFormats.model_validate(data)

    async def get_organization(self, **kwargs: Any) -> GetOrganization:
        query = gql(
            """
            query GetOrganization {
              organization(id: "1") {
                ...organizationFields
              }
            }

            fragment organizationFields on Organization {
              id
              name
              teams {
                name
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="GetOrganization", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetOrganization.model_validate(data)

    async def get_organizations(self, **kwargs: Any) -> GetOrganizations:
        query = gql(
            """
            query GetOrganizations {
              organizations(first: 5) {
                edges {
                  node {
                    ...organizationFields
                  }
                }
              }
            }

            fragment organizationFields on Organization {
              id
              name
              teams {
                name
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query,
            operation_name="GetOrganizations",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetOrganizations.model_validate(data)

    async def get_team_by_exact_name(
        self, team_name: Union[Optional[str], UnsetType] = UNSET, **kwargs: Any
    ) -> GetTeamByExactName:
        query = gql(
            """
            query GetTeamByExactName($teamName: String) {
              teams(filter: {name: {equals: $teamName}}) {
                edges {
                  cursor
                  node {
                    ...teamFields
                  }
                }
              }
            }

            fragment teamFields on Team {
              id
              name
              colorPrimary
              colorSecondary
              logoUrl
              externalLinks {
                dataProvider {
                  name
                }
                externalEntity {
                  id
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"teamName": team_name}
        response = await self.execute(
            query=query,
            operation_name="GetTeamByExactName",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetTeamByExactName.model_validate(data)

    async def get_team_by_similar_name(
        self, team_name: Union[Optional[str], UnsetType] = UNSET, **kwargs: Any
    ) -> GetTeamBySimilarName:
        query = gql(
            """
            query GetTeamBySimilarName($teamName: String) {
              teams(filter: {name: {contains: $teamName}}) {
                edges {
                  cursor
                  node {
                    ...teamFields
                  }
                }
              }
            }

            fragment teamFields on Team {
              id
              name
              colorPrimary
              colorSecondary
              logoUrl
              externalLinks {
                dataProvider {
                  name
                }
                externalEntity {
                  id
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"teamName": team_name}
        response = await self.execute(
            query=query,
            operation_name="GetTeamBySimilarName",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetTeamBySimilarName.model_validate(data)

    async def get_teams(self, **kwargs: Any) -> GetTeams:
        query = gql(
            """
            query GetTeams {
              teams(first: 5, after: null) {
                totalCount
                pageInfo {
                  hasPreviousPage
                  hasNextPage
                  startCursor
                  endCursor
                }
                totalCount
                edges {
                  cursor
                  node {
                    ...teamFields
                  }
                }
              }
            }

            fragment teamFields on Team {
              id
              name
              colorPrimary
              colorSecondary
              logoUrl
              externalLinks {
                dataProvider {
                  name
                }
                externalEntity {
                  id
                }
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="GetTeams", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetTeams.model_validate(data)

    async def get_player(self, **kwargs: Any) -> GetPlayer:
        query = gql(
            """
            query GetPlayer {
              player(id: "1") {
                ...playerFields
              }
            }

            fragment playerFields on Player {
              id
              nickname
              title {
                name
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="GetPlayer", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetPlayer.model_validate(data)

    async def get_players(self, **kwargs: Any) -> GetPlayers:
        query = gql(
            """
            query GetPlayers {
              players(first: 5) {
                edges {
                  node {
                    ...playerFields
                  }
                }
              }
            }

            fragment playerFields on Player {
              id
              nickname
              title {
                name
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="GetPlayers", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetPlayers.model_validate(data)

    async def get_team_roster(self, **kwargs: Any) -> GetTeamRoster:
        query = gql(
            """
            query GetTeamRoster {
              players(filter: {teamIdFilter: {id: "1"}}) {
                edges {
                  node {
                    ...playerFields
                  }
                }
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                }
              }
            }

            fragment playerFields on Player {
              id
              nickname
              title {
                name
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="GetTeamRoster", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetTeamRoster.model_validate(data)
