# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class OrganizationFields(BaseModel):
    id: str
    name: str
    teams: Optional[list["OrganizationFieldsTeams"]]


class OrganizationFieldsTeams(BaseModel):
    name: str


class PlayerFields(BaseModel):
    id: str
    nickname: str
    title: "PlayerFieldsTitle"


class PlayerFieldsTitle(BaseModel):
    name: str


class SeriesFields(BaseModel):
    id: str
    title: "SeriesFieldsTitle"
    tournament: "SeriesFieldsTournament"
    start_time_scheduled: Any = Field(alias="startTimeScheduled")
    format: "SeriesFieldsFormat"
    teams: list["SeriesFieldsTeams"]


class SeriesFieldsTitle(BaseModel):
    name_shortened: str = Field(alias="nameShortened")


class SeriesFieldsTournament(BaseModel):
    name_shortened: str = Field(alias="nameShortened")


class SeriesFieldsFormat(BaseModel):
    name: str
    name_shortened: str = Field(alias="nameShortened")


class SeriesFieldsTeams(BaseModel):
    base_info: "SeriesFieldsTeamsBaseInfo" = Field(alias="baseInfo")
    score_advantage: int = Field(alias="scoreAdvantage")


class SeriesFieldsTeamsBaseInfo(BaseModel):
    name: str


class TeamFields(BaseModel):
    id: str
    name: str
    color_primary: Any = Field(alias="colorPrimary")
    color_secondary: Any = Field(alias="colorSecondary")
    logo_url: Any = Field(alias="logoUrl")
    external_links: list["TeamFieldsExternalLinks"] = Field(alias="externalLinks")


class TeamFieldsExternalLinks(BaseModel):
    data_provider: "TeamFieldsExternalLinksDataProvider" = Field(alias="dataProvider")
    external_entity: "TeamFieldsExternalLinksExternalEntity" = Field(
        alias="externalEntity"
    )


class TeamFieldsExternalLinksDataProvider(BaseModel):
    name: str


class TeamFieldsExternalLinksExternalEntity(BaseModel):
    id: str


class TournamentFields(BaseModel):
    id: str
    name: str
    name_shortened: str = Field(alias="nameShortened")


OrganizationFields.model_rebuild()
PlayerFields.model_rebuild()
SeriesFields.model_rebuild()
TeamFields.model_rebuild()
TournamentFields.model_rebuild()
