# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import SeriesFields


class GetAllSeriesInNext24Hours(BaseModel):
    all_series: "GetAllSeriesInNext24HoursAllSeries" = Field(alias="allSeries")


class GetAllSeriesInNext24HoursAllSeries(BaseModel):
    total_count: int = Field(alias="totalCount")
    page_info: "GetAllSeriesInNext24HoursAllSeriesPageInfo" = Field(alias="pageInfo")
    edges: list["GetAllSeriesInNext24HoursAllSeriesEdges"]


class GetAllSeriesInNext24HoursAllSeriesPageInfo(BaseModel):
    has_previous_page: bool = Field(alias="hasPreviousPage")
    has_next_page: bool = Field(alias="hasNextPage")
    start_cursor: Optional[str] = Field(default=None, alias="startCursor")
    end_cursor: Optional[str] = Field(default=None, alias="endCursor")


class GetAllSeriesInNext24HoursAllSeriesEdges(BaseModel):
    cursor: str
    node: "GetAllSeriesInNext24HoursAllSeriesEdgesNode"


class GetAllSeriesInNext24HoursAllSeriesEdgesNode(SeriesFields):
    pass


GetAllSeriesInNext24Hours.model_rebuild()
GetAllSeriesInNext24HoursAllSeries.model_rebuild()
GetAllSeriesInNext24HoursAllSeriesEdges.model_rebuild()
