# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import TournamentFields


class GetTournaments(BaseModel):
    tournaments: "GetTournamentsTournaments"


class GetTournamentsTournaments(BaseModel):
    page_info: "GetTournamentsTournamentsPageInfo" = Field(alias="pageInfo")
    total_count: int = Field(alias="totalCount")
    edges: list["GetTournamentsTournamentsEdges"]


class GetTournamentsTournamentsPageInfo(BaseModel):
    has_previous_page: bool = Field(alias="hasPreviousPage")
    has_next_page: bool = Field(alias="hasNextPage")
    start_cursor: Optional[Any] = Field(alias="startCursor")
    end_cursor: Optional[Any] = Field(alias="endCursor")


class GetTournamentsTournamentsEdges(BaseModel):
    cursor: Any
    node: "GetTournamentsTournamentsEdgesNode"


class GetTournamentsTournamentsEdgesNode(TournamentFields):
    pass


GetTournaments.model_rebuild()
GetTournamentsTournaments.model_rebuild()
GetTournamentsTournamentsEdges.model_rebuild()
