# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import SeriesFields


class GetCsgoLoopfeedSeries(BaseModel):
    series: Optional["GetCsgoLoopfeedSeriesSeries"]


class GetCsgoLoopfeedSeriesSeries(SeriesFields):
    pass


GetCsgoLoopfeedSeries.model_rebuild()
