# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Any

from .base_model import BaseModel
from .fragments import TeamFields


class GetTeamByName(BaseModel):
    teams: "GetTeamByNameTeams"


class GetTeamByNameTeams(BaseModel):
    edges: list["GetTeamByNameTeamsEdges"]


class GetTeamByNameTeamsEdges(BaseModel):
    cursor: Any
    node: "GetTeamByNameTeamsEdgesNode"


class GetTeamByNameTeamsEdgesNode(TeamFields):
    pass


GetTeamByName.model_rebuild()
GetTeamByNameTeams.model_rebuild()
GetTeamByNameTeamsEdges.model_rebuild()
