# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import TeamFields


class GetTeams(BaseModel):
    teams: "GetTeamsTeams"


class GetTeamsTeams(BaseModel):
    total_count: int = Field(alias="totalCount")
    page_info: "GetTeamsTeamsPageInfo" = Field(alias="pageInfo")
    total_count: int = Field(alias="totalCount")
    edges: list["GetTeamsTeamsEdges"]


class GetTeamsTeamsPageInfo(BaseModel):
    has_previous_page: bool = Field(alias="hasPreviousPage")
    has_next_page: bool = Field(alias="hasNextPage")
    start_cursor: Optional[Any] = Field(alias="startCursor")
    end_cursor: Optional[Any] = Field(alias="endCursor")


class GetTeamsTeamsEdges(BaseModel):
    cursor: Any
    node: "GetTeamsTeamsEdgesNode"


class GetTeamsTeamsEdgesNode(TeamFields):
    pass


GetTeams.model_rebuild()
GetTeamsTeams.model_rebuild()
GetTeamsTeamsEdges.model_rebuild()
