# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import TournamentFields


class GetTournament(BaseModel):
    tournament: Optional["GetTournamentTournament"]


class GetTournamentTournament(TournamentFields):
    pass


GetTournament.model_rebuild()
