# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import OrganizationFields


class GetOrganization(BaseModel):
    organization: Optional["GetOrganizationOrganization"]


class GetOrganizationOrganization(OrganizationFields):
    pass


GetOrganization.model_rebuild()
