# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import PlayerFields


class GetPlayer(BaseModel):
    player: Optional["GetPlayerPlayer"]


class GetPlayerPlayer(PlayerFields):
    pass


GetPlayer.model_rebuild()
