# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from .base_model import BaseModel
from .fragments import PlayerFields


class GetPlayers(BaseModel):
    players: "GetPlayersPlayers"


class GetPlayersPlayers(BaseModel):
    edges: list["GetPlayersPlayersEdges"]


class GetPlayersPlayersEdges(BaseModel):
    node: "GetPlayersPlayersEdgesNode"


class GetPlayersPlayersEdgesNode(PlayerFields):
    pass


GetPlayers.model_rebuild()
GetPlayersPlayers.model_rebuild()
GetPlayersPlayersEdges.model_rebuild()
