# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import TeamFields


class GetTeam(BaseModel):
    team: Optional["GetTeamTeam"]


class GetTeamTeam(TeamFields):
    pass


GetTeam.model_rebuild()
