# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from .base_model import BaseModel
from .fragments import OrganizationFields


class GetOrganizations(BaseModel):
    organizations: "GetOrganizationsOrganizations"


class GetOrganizationsOrganizations(BaseModel):
    edges: list["GetOrganizationsOrganizationsEdges"]


class GetOrganizationsOrganizationsEdges(BaseModel):
    node: "GetOrganizationsOrganizationsEdgesNode"


class GetOrganizationsOrganizationsEdgesNode(OrganizationFields):
    pass


GetOrganizations.model_rebuild()
GetOrganizationsOrganizations.model_rebuild()
GetOrganizationsOrganizationsEdges.model_rebuild()
