# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from .base_model import BaseModel
from .fragments import TeamFields


class GetTeamBySimilarName(BaseModel):
    teams: "GetTeamBySimilarNameTeams"


class GetTeamBySimilarNameTeams(BaseModel):
    edges: list["GetTeamBySimilarNameTeamsEdges"]


class GetTeamBySimilarNameTeamsEdges(BaseModel):
    cursor: str
    node: "GetTeamBySimilarNameTeamsEdgesNode"


class GetTeamBySimilarNameTeamsEdgesNode(TeamFields):
    pass


GetTeamBySimilarName.model_rebuild()
GetTeamBySimilarNameTeams.model_rebuild()
GetTeamBySimilarNameTeamsEdges.model_rebuild()
