# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from .base_model import BaseModel
from .fragments import TeamFields


class GetTeamByExactName(BaseModel):
    teams: "GetTeamByExactNameTeams"


class GetTeamByExactNameTeams(BaseModel):
    edges: list["GetTeamByExactNameTeamsEdges"]


class GetTeamByExactNameTeamsEdges(BaseModel):
    cursor: str
    node: "GetTeamByExactNameTeamsEdgesNode"


class GetTeamByExactNameTeamsEdgesNode(TeamFields):
    pass


GetTeamByExactName.model_rebuild()
GetTeamByExactNameTeams.model_rebuild()
GetTeamByExactNameTeamsEdges.model_rebuild()
