# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import SeriesFields


class GetAllSeriesSinceDate(BaseModel):
    all_series: "GetAllSeriesSinceDateAllSeries" = Field(alias="allSeries")


class GetAllSeriesSinceDateAllSeries(BaseModel):
    total_count: int = Field(alias="totalCount")
    page_info: "GetAllSeriesSinceDateAllSeriesPageInfo" = Field(alias="pageInfo")
    edges: list["GetAllSeriesSinceDateAllSeriesEdges"]


class GetAllSeriesSinceDateAllSeriesPageInfo(BaseModel):
    has_previous_page: bool = Field(alias="hasPreviousPage")
    has_next_page: bool = Field(alias="hasNextPage")
    start_cursor: Optional[Any] = Field(default=None, alias="startCursor")
    end_cursor: Optional[Any] = Field(default=None, alias="endCursor")


class GetAllSeriesSinceDateAllSeriesEdges(BaseModel):
    cursor: Any
    node: "GetAllSeriesSinceDateAllSeriesEdgesNode"


class GetAllSeriesSinceDateAllSeriesEdgesNode(SeriesFields):
    pass


GetAllSeriesSinceDate.model_rebuild()
GetAllSeriesSinceDateAllSeries.model_rebuild()
GetAllSeriesSinceDateAllSeriesEdges.model_rebuild()
