# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from pydantic import Field

from .base_model import BaseModel
from .fragments import PlayerFields


class GetTeamRoster(BaseModel):
    players: "GetTeamRosterPlayers"


class GetTeamRosterPlayers(BaseModel):
    edges: list["GetTeamRosterPlayersEdges"]
    page_info: "GetTeamRosterPlayersPageInfo" = Field(alias="pageInfo")


class GetTeamRosterPlayersEdges(BaseModel):
    node: "GetTeamRosterPlayersEdgesNode"


class GetTeamRosterPlayersEdgesNode(PlayerFields):
    pass


class GetTeamRosterPlayersPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    has_previous_page: bool = Field(alias="hasPreviousPage")


GetTeamRoster.model_rebuild()
GetTeamRosterPlayers.model_rebuild()
GetTeamRosterPlayersEdges.model_rebuild()
