# Generated by ariadne-codegen
# Source: https://api-op.grid.gg/central-data/graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import SeriesType, ServiceLevel, TournamentVenueType


class BooleanFilter(BaseModel):
    equals: Optional[bool] = None


class DateTimeFilter(BaseModel):
    gte: Optional[str] = None
    lte: Optional[str] = None


class GameFilter(BaseModel):
    id: Optional["IdFilter"] = None
    map: Optional["MapFilter"] = None


class IdFilter(BaseModel):
    in_: Optional[list[str]] = Field(alias="in", default=None)


class IntFilter(BaseModel):
    gte: Optional[int] = None
    lte: Optional[int] = None
    equals: Optional[int] = None


class MapFilter(BaseModel):
    name: Optional["StringFilter"] = None


class NationalityFilter(BaseModel):
    code: Optional["StringFilter"] = None
    name: Optional["StringFilter"] = None


class NullableDateFilter(BaseModel):
    gte: Optional[Any] = None
    lte: Optional[Any] = None


class NullableIdFilter(BaseModel):
    id: Optional[str] = None


class OrganizationFilter(BaseModel):
    name: Optional["StringFilter"] = None
    private: Optional["BooleanFilter"] = None
    updated_at: Optional["DateTimeFilter"] = Field(alias="updatedAt", default=None)


class PlayerFilter(BaseModel):
    title_id: Optional[str] = Field(alias="titleId", default=None)
    team_id_filter: Optional["NullableIdFilter"] = Field(
        alias="teamIdFilter", default=None
    )
    nickname: Optional["StringFilter"] = None
    private: Optional["BooleanFilter"] = None
    full_name: Optional["StringFilter"] = Field(alias="fullName", default=None)
    age: Optional["IntFilter"] = None
    nationality: Optional["NationalityFilter"] = None
    roles: Optional["PlayerPlayerRoleFilter"] = None
    updated_at: Optional["DateTimeFilter"] = Field(alias="updatedAt", default=None)


class PlayerPlayerRoleFilter(BaseModel):
    name: Optional["StringFilter"] = None
    title: Optional["PlayerRoleTitleFilter"] = None


class PlayerRoleFilter(BaseModel):
    name: Optional["StringFilter"] = None
    title: Optional["PlayerRoleTitleFilter"] = None


class PlayerRoleTitleFilter(BaseModel):
    id: "IdFilter"


class ProductServiceLevelFilter(BaseModel):
    product_name: str = Field(alias="productName")
    service_level: ServiceLevel = Field(alias="serviceLevel")


class SeriesFilter(BaseModel):
    start_time_scheduled: Optional["DateTimeFilter"] = Field(
        alias="startTimeScheduled", default=None
    )
    tournament_id: Optional[str] = Field(alias="tournamentId", default=None)
    tournament_ids: Optional["IdFilter"] = Field(alias="tournamentIds", default=None)
    tournament: Optional["SeriesTournamentFilter"] = None
    team_id: Optional[str] = Field(alias="teamId", default=None)
    team_ids: Optional["IdFilter"] = Field(alias="teamIds", default=None)
    title_id: Optional[str] = Field(alias="titleId", default=None)
    title_ids: Optional["IdFilter"] = Field(alias="titleIds", default=None)
    live_player_ids: Optional["IdFilter"] = Field(alias="livePlayerIds", default=None)
    type: Optional[SeriesType] = None
    types: Optional[list[SeriesType]] = None
    product_service_levels: Optional["ProductServiceLevelFilter"] = Field(
        alias="productServiceLevels", default=None
    )
    live: Optional["SeriesLiveFilter"] = None
    private: Optional["BooleanFilter"] = None
    players: Optional["SeriesPlayerFilter"] = None
    updated_at: Optional["DateTimeFilter"] = Field(alias="updatedAt", default=None)


class SeriesLiveFilter(BaseModel):
    games: Optional["GameFilter"] = None


class SeriesPlayerFilter(BaseModel):
    age: Optional["IntFilter"] = None


class SeriesTournamentFilter(BaseModel):
    id: Optional["IdFilter"] = None
    title: Optional["SeriesTournamentTitleFilter"] = None
    name: Optional["StringFilter"] = None
    name_shortened: Optional["StringFilter"] = Field(
        alias="nameShortened", default=None
    )
    start_date: Optional["NullableDateFilter"] = Field(alias="startDate", default=None)
    end_date: Optional["NullableDateFilter"] = Field(alias="endDate", default=None)
    include_children: Optional["BooleanFilter"] = Field(
        alias="includeChildren", default=None
    )


class SeriesTournamentTitleFilter(BaseModel):
    id: Optional["IdFilter"] = None


class StringFilter(BaseModel):
    contains: Optional[str] = None
    equals: Optional[str] = None


class TeamFilter(BaseModel):
    title_id: Optional[str] = Field(alias="titleId", default=None)
    name: Optional["StringFilter"] = None
    name_shortened: Optional["StringFilter"] = Field(
        alias="nameShortened", default=None
    )
    organization_id: Optional[str] = Field(alias="organizationId", default=None)
    private: Optional["BooleanFilter"] = None
    updated_at: Optional["DateTimeFilter"] = Field(alias="updatedAt", default=None)


class TitleFilter(BaseModel):
    private: Optional["BooleanFilter"] = None


class TournamentFilter(BaseModel):
    title_id: Optional[str] = Field(alias="titleId", default=None)
    title: Optional["TournamentTitleFilter"] = None
    name: Optional["StringFilter"] = None
    name_shortened: Optional["StringFilter"] = Field(
        alias="nameShortened", default=None
    )
    start_date: Optional["NullableDateFilter"] = Field(alias="startDate", default=None)
    end_date: Optional["NullableDateFilter"] = Field(alias="endDate", default=None)
    has_children: Optional["BooleanFilter"] = Field(alias="hasChildren", default=None)
    has_parent: Optional["BooleanFilter"] = Field(alias="hasParent", default=None)
    private: Optional["BooleanFilter"] = None
    venue_type: Optional[list[TournamentVenueType]] = Field(
        alias="venueType", default=None
    )
    updated_at: Optional["DateTimeFilter"] = Field(alias="updatedAt", default=None)
    product_service_levels: Optional["ProductServiceLevelFilter"] = Field(
        alias="productServiceLevels", default=None
    )


class TournamentTitleFilter(BaseModel):
    id: Optional["IdFilter"] = None


GameFilter.model_rebuild()
MapFilter.model_rebuild()
NationalityFilter.model_rebuild()
OrganizationFilter.model_rebuild()
PlayerFilter.model_rebuild()
PlayerPlayerRoleFilter.model_rebuild()
PlayerRoleFilter.model_rebuild()
PlayerRoleTitleFilter.model_rebuild()
SeriesFilter.model_rebuild()
SeriesLiveFilter.model_rebuild()
SeriesPlayerFilter.model_rebuild()
SeriesTournamentFilter.model_rebuild()
SeriesTournamentTitleFilter.model_rebuild()
TeamFilter.model_rebuild()
TitleFilter.model_rebuild()
TournamentFilter.model_rebuild()
TournamentTitleFilter.model_rebuild()
