# Generated by ariadne-codegen
# Source: ./query_files/central-data-queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class SeriesFormats(BaseModel):
    series_formats: list["SeriesFormatsSeriesFormats"] = Field(alias="seriesFormats")


class SeriesFormatsSeriesFormats(BaseModel):
    id: Optional[str]
    name: str
    name_shortened: str = Field(alias="nameShortened")


SeriesFormats.model_rebuild()
